import { Command } from 'commander';
import { mkdirSync, existsSync, writeFileSync, symlinkSync, readlinkSync, readFileSync, readdirSync } from 'node:fs';
import { join, basename, resolve, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { createInterface } from 'node:readline';
import { getFFHome, getFFDirs } from '../home.js';
import { success, info, warn, error } from '../logger.js';
import { installPersonas } from '../personas/installer.js';
import { runDoctor } from './doctor.js';
import pc from 'picocolors';

// ── Types ────────────────────────────────────────────────────────────────

interface RepoAnswers {
  name: string;
  path: string;
  github: string;
  language: string;
  build: string;
  test: string;
  lint: string;
  format: string;
}

interface InitAnswers {
  project: string;
  title: string;
  workspace: string;
  repos: RepoAnswers[];
  description: string;
  invariants: string[];
}

// ── Readline helpers ─────────────────────────────────────────────────────

function createRL(): ReturnType<typeof createInterface> {
  return createInterface({
    input: process.stdin,
    output: process.stderr, // prompts go to stderr so stdout stays clean
    terminal: true,
  });
}

function ask(rl: ReturnType<typeof createInterface>, question: string, defaultVal?: string): Promise<string> {
  const suffix = defaultVal ? ` ${pc.dim(`(${defaultVal})`)}` : '';
  return new Promise((resolve) => {
    rl.question(`${pc.cyan('?')} ${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultVal || '');
    });
  });
}

function askYesNo(rl: ReturnType<typeof createInterface>, question: string, defaultYes: boolean = false): Promise<boolean> {
  const hint = defaultYes ? 'Y/n' : 'y/N';
  return new Promise((resolve) => {
    rl.question(`${pc.cyan('?')} ${question} ${pc.dim(`(${hint})`)}: `, (answer) => {
      const a = answer.trim().toLowerCase();
      if (a === '') resolve(defaultYes);
      else resolve(a === 'y' || a === 'yes');
    });
  });
}

// ── Language defaults ────────────────────────────────────────────────────

const LANGUAGE_DEFAULTS: Record<string, { build: string; test: string; lint: string; format: string }> = {
  typescript: {
    build: 'npm run build',
    test: 'npm test',
    lint: 'npm run lint',
    format: 'npm run format',
  },
  go: {
    build: 'go build ./...',
    test: 'go test ./...',
    lint: 'golangci-lint run',
    format: 'gofmt -w .',
  },
  python: {
    build: '',
    test: 'pytest',
    lint: 'ruff check .',
    format: 'ruff format .',
  },
  java: {
    build: './gradlew build',
    test: './gradlew test',
    lint: './gradlew checkstyleMain',
    format: './gradlew spotlessApply',
  },
  rust: {
    build: 'cargo build',
    test: 'cargo test',
    lint: 'cargo clippy',
    format: 'cargo fmt',
  },
  other: {
    build: '',
    test: '',
    lint: '',
    format: '',
  },
};

// ── YAML generation ──────────────────────────────────────────────────────

function generateFactoryYaml(answers: InitAnswers): string {
  const lines: string[] = [];

  lines.push('# ──────────────────────────────────────────────────────────────────────');
  lines.push('# factory.yaml — Anvil project configuration');
  lines.push('# Generated by: anvil init');
  lines.push('# ──────────────────────────────────────────────────────────────────────');
  lines.push('');

  // Version
  lines.push('# Schema version (always 1 for now)');
  lines.push('version: 1');
  lines.push('');

  // Project identifier
  lines.push('# Project identifier (slug used in CLI commands and directory names)');
  lines.push(`project: ${answers.project}`);
  lines.push('');

  // Title
  if (answers.title && answers.title !== answers.project) {
    lines.push('# Human-readable project title');
    lines.push(`title: ${answers.title}`);
    lines.push('');
  }

  // Workspace
  lines.push('# Workspace root — where repos are cloned/located on disk');
  lines.push(`workspace: ${answers.workspace}`);
  lines.push('');

  // Repos
  lines.push('# ── Repositories ────────────────────────────────────────────────────');
  lines.push('# Each repo defines a codebase that Anvil agents work with.');
  lines.push('# Paths are relative to the workspace root.');
  lines.push('repos:');

  for (const repo of answers.repos) {
    lines.push(`  - name: ${repo.name}`);
    lines.push(`    path: ${repo.path}`);
    if (repo.github) {
      lines.push(`    github: ${repo.github}`);
    }
    lines.push(`    language: ${repo.language}`);

    // Only emit commands block if at least one command is non-empty
    const cmds = { build: repo.build, test: repo.test, lint: repo.lint, format: repo.format };
    const hasCmds = Object.values(cmds).some((v) => v !== '');
    if (hasCmds) {
      lines.push('    commands:');
      if (cmds.build) lines.push(`      build: ${cmds.build}`);
      if (cmds.test) lines.push(`      test: ${cmds.test}`);
      if (cmds.lint) lines.push(`      lint: ${cmds.lint}`);
      if (cmds.format) lines.push(`      format: ${cmds.format}`);
    }
    lines.push('');
  }

  // Domain section
  const hasDomain = answers.description || answers.invariants.length > 0;
  if (hasDomain) {
    lines.push('# ── Domain knowledge ────────────────────────────────────────────────');
    lines.push('# Help agents understand your project context and constraints.');
    lines.push('domain:');

    if (answers.description) {
      lines.push('  description: |');
      for (const descLine of answers.description.split('\n')) {
        lines.push(`    ${descLine}`);
      }
      lines.push('');
    }

    if (answers.invariants.length > 0) {
      lines.push('  # Rules that must never be violated by generated code');
      lines.push('  invariants:');
      for (const inv of answers.invariants) {
        lines.push(`    - "${inv}"`);
      }
      lines.push('');
    }

    // Placeholder sections
    lines.push('  # glossary:');
    lines.push('  #   term: Definition of the term');
    lines.push('');
    lines.push('  # critical_flows:');
    lines.push('  #   - name: User signup');
    lines.push('  #     steps: [create account, send verification email, activate]');
    lines.push('');
    lines.push('  # sharp_edges:');
    lines.push('  #   - "Never delete user data without explicit confirmation"');
    lines.push('');
  }

  // Pipeline section (always as commented placeholder)
  lines.push('# ── Pipeline configuration (optional) ────────────────────────────────');
  lines.push('# pipeline:');
  lines.push('#   stages: [clarify, requirements, impl-plan, implement, verify, ship]');
  lines.push('#   ship:');
  lines.push('#     branch_prefix: feat/ff-');
  lines.push('#   models:');
  lines.push('#     default: claude-sonnet-4-20250514');
  lines.push('#     research: claude-opus-4-20250514');
  lines.push('');

  return lines.join('\n') + '\n';
}

function generateWorkspaceConfig(projectName: string): string {
  const lines: string[] = [];
  lines.push('# Anvil workspace config');
  lines.push('# This file marks this directory as an Anvil workspace.');
  lines.push(`# Full config: ~/.anvil/projects/${projectName}/factory.yaml`);
  lines.push('');
  lines.push(`project: ${projectName}`);
  lines.push('');
  return lines.join('\n');
}

// ── Home directory setup (from original init) ────────────────────────────

const DEFAULT_CONFIG = `# Anvil Configuration
# See: https://github.com/anvil-dev/docs

# Default project to use when none specified
# default_project: my-project

# Agent settings
agent:
  # model: claude-sonnet-4-20250514
  max_retries: 3

# Dashboard settings
dashboard:
  port: 3333
  auto_open: true
`;

export async function runInit(force: boolean = false): Promise<void> {
  const home = getFFHome();
  const dirs = getFFDirs(home);

  const allDirs = [
    dirs.projects,
    dirs.personas,
    dirs.conventions,
    dirs.conventionRules,
    dirs.memory,
    dirs.memoryGlobal,
    dirs.runs,
    dirs.workspaces,
    dirs.logs,
  ];

  let created = 0;
  for (const dir of allDirs) {
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
      created++;
    }
  }

  const configPath = join(home, 'config.yaml');
  if (!existsSync(configPath)) {
    writeFileSync(configPath, DEFAULT_CONFIG, 'utf-8');
    created++;
  }

  // Install persona prompts
  const personaResult = await installPersonas(force);
  if (personaResult.installed.length > 0) {
    success(`Installed ${personaResult.installed.length} persona prompts`);
  }
  if (personaResult.skipped.length > 0) {
    info(`Skipped ${personaResult.skipped.length} existing persona prompts`);
  }

  if (created > 0 || personaResult.installed.length > 0) {
    success(`Initialized Anvil at ${home}`);
  } else {
    info(`Anvil already initialized at ${home}`);
  }
}

// ── Interactive project scaffolding ──────────────────────────────────────

async function runProjectInit(): Promise<void> {
  // Ensure FF home is set up first
  await runInit(false);

  console.error('');
  console.error(pc.bold('Anvil — Project Setup'));
  console.error(pc.dim('Scaffold a factory.yaml configuration for your project.'));
  console.error('');

  const rl = createRL();

  try {
    // ── Basic info ─────────────────────────────────────────────────────

    const cwd = process.cwd();
    const defaultName = basename(cwd)
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');

    const project = await ask(rl, 'Project name (slug)', defaultName);
    const title = await ask(rl, 'Title', project);
    const workspace = await ask(rl, 'Workspace path', cwd);

    // ── Repos ──────────────────────────────────────────────────────────

    const repos: RepoAnswers[] = [];

    console.error('');
    console.error(pc.dim('Add the repositories that make up this project.'));

    let addMore = await askYesNo(rl, 'Add a repository?', true);

    while (addMore) {
      console.error('');
      const repoName = await ask(rl, '  Repo name');
      if (!repoName) {
        warn('Repo name is required, skipping.');
        addMore = await askYesNo(rl, 'Add another repository?', false);
        continue;
      }

      const repoPath = await ask(rl, '  Path (relative to workspace)', `./${repoName}`);
      const github = await ask(rl, '  GitHub org/repo (optional, e.g. acme/api)', '');

      console.error(pc.dim('    Languages: typescript, go, python, java, rust, other'));
      const language = await ask(rl, '  Language', 'typescript');
      const langKey = language.toLowerCase();
      const defaults = LANGUAGE_DEFAULTS[langKey] || LANGUAGE_DEFAULTS.other;

      const build = await ask(rl, '  Build command', defaults.build);
      const test = await ask(rl, '  Test command', defaults.test);
      const lint = await ask(rl, '  Lint command', defaults.lint);
      const format = await ask(rl, '  Format command', defaults.format);

      repos.push({ name: repoName, path: repoPath, github, language: langKey, build, test, lint, format });
      success(`Added repo: ${repoName}`);

      addMore = await askYesNo(rl, 'Add another repository?', false);
    }

    if (repos.length === 0) {
      warn('No repos added. You can add them later by editing factory.yaml.');
    }

    // ── Domain ─────────────────────────────────────────────────────────

    console.error('');
    console.error(pc.dim('Domain context helps agents understand your project.'));

    const description = await ask(rl, 'Domain description (optional, one line)', '');

    const invariants: string[] = [];
    let addInvariant = await askYesNo(rl, 'Add a project invariant?', false);
    while (addInvariant) {
      const inv = await ask(rl, '  Invariant');
      if (inv) {
        invariants.push(inv);
        success(`Added invariant: ${inv}`);
      }
      addInvariant = await askYesNo(rl, 'Add another invariant?', false);
    }

    rl.close();

    // ── Generate files ─────────────────────────────────────────────────

    const answers: InitAnswers = { project, title, workspace, repos, description, invariants };
    const yamlContent = generateFactoryYaml(answers);

    // 1. Write to ~/.anvil/projects/<name>/factory.yaml
    const anvilHome = getFFHome();
    const projectDir = join(anvilHome, 'projects', project);
    if (!existsSync(projectDir)) {
      mkdirSync(projectDir, { recursive: true });
    }
    const factoryYamlPath = join(projectDir, 'factory.yaml');
    const overwrite = existsSync(factoryYamlPath);

    writeFileSync(factoryYamlPath, yamlContent, 'utf-8');

    if (overwrite) {
      warn(`Overwrote existing ${factoryYamlPath}`);
    } else {
      success(`Created ${factoryYamlPath}`);
    }

    // 2. Create .factory/config.yaml in the workspace root
    const resolvedWorkspace = workspace.startsWith('~')
      ? join(homedir(), workspace.slice(1))
      : resolve(workspace);

    const dotFactoryDir = join(resolvedWorkspace, '.factory');
    const dotFactoryConfig = join(dotFactoryDir, 'config.yaml');

    if (existsSync(resolvedWorkspace)) {
      if (!existsSync(dotFactoryDir)) {
        mkdirSync(dotFactoryDir, { recursive: true });
      }
      writeFileSync(dotFactoryConfig, generateWorkspaceConfig(project), 'utf-8');
      success(`Created ${dotFactoryConfig}`);

      // Try to symlink the full factory.yaml into .factory/ for convenience
      const symlinkPath = join(dotFactoryDir, 'factory.yaml');
      if (!existsSync(symlinkPath)) {
        try {
          symlinkSync(factoryYamlPath, symlinkPath);
          info(`Symlinked ${symlinkPath} -> ${factoryYamlPath}`);
        } catch {
          // Symlink might fail on some projects; not critical
          info(`Tip: You can symlink manually: ln -s ${factoryYamlPath} ${symlinkPath}`);
        }
      }
    } else {
      warn(`Workspace directory ${resolvedWorkspace} does not exist yet. Skipped .factory/config.yaml creation.`);
      info(`Create the directory and re-run, or manually create .factory/config.yaml there.`);
    }

    // ── Success message ────────────────────────────────────────────────

    console.error('');
    console.error(pc.bold(pc.green('Project initialized!')));
    console.error('');
    console.error(`  ${pc.dim('Config:')}   ${factoryYamlPath}`);
    if (existsSync(dotFactoryConfig)) {
      console.error(`  ${pc.dim('Local:')}    ${dotFactoryConfig}`);
    }
    console.error('');

    // ── First-run flow: auto-run doctor ──────────────────────────────

    console.error(pc.bold('Running health checks...'));
    console.error('');
    const doctorOk = await runDoctor();

    // ── First-run flow: auto-run setup if repos have github fields ───

    const hasGithubRepos = repos.some((r) => r.github);
    if (hasGithubRepos) {
      console.error('');
      const rl2 = createRL();
      const runSetup = await askYesNo(rl2, 'Clone repositories now?', true);
      rl2.close();

      if (runSetup) {
        // Dynamically import setup to avoid circular deps
        const { setupCommand } = await import('./setup.js');
        console.error('');
        await setupCommand.parseAsync([project], { from: 'user' });
      }
    }

    // ── Final next steps ─────────────────────────────────────────────

    console.error('');
    console.error(pc.bold('Next steps:'));
    console.error(`  1. Review and edit: ${pc.cyan(factoryYamlPath)}`);
    console.error(`  2. Run a feature:   ${pc.cyan(`anvil run ${project} "your feature description"`)}`);
    console.error(`  3. Open dashboard:  ${pc.cyan('anvil dashboard')}`);
    console.error('');

  } catch (err) {
    rl.close();
    if ((err as any)?.code === 'ERR_USE_AFTER_CLOSE') {
      // User cancelled with Ctrl+C
      console.error('');
      info('Cancelled.');
      return;
    }
    throw err;
  }
}

// ── Template support ─────────────────────────────────────────────────────

const AVAILABLE_TEMPLATES = [
  'typescript-nextjs',
  'go-microservices',
  'python-fastapi',
  'rust-axum',
  'monorepo-turborepo',
  'django-celery',
];

function getTemplatesDir(): string {
  // Templates are bundled with the CLI package
  const thisFile = fileURLToPath(import.meta.url);
  return join(dirname(thisFile), '..', 'templates');
}

async function runTemplateInit(templateName: string, projectName?: string): Promise<void> {
  await runInit(false);

  const templatesDir = getTemplatesDir();
  const templatePath = join(templatesDir, `${templateName}.yaml`);

  if (!existsSync(templatePath)) {
    error(`Template "${templateName}" not found.`);
    info(`Available templates: ${AVAILABLE_TEMPLATES.join(', ')}`);
    process.exitCode = 1;
    return;
  }

  let content = readFileSync(templatePath, 'utf-8');

  // Resolve placeholders
  const cwd = process.cwd();
  const name = projectName || basename(cwd).toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '') || templateName;
  content = content.replace(/\{\{PROJECT_NAME\}\}/g, name);
  content = content.replace(/\{\{WORKSPACE\}\}/g, cwd);

  // Write to ~/.anvil/projects/<name>/factory.yaml
  const anvilHome = getFFHome();
  const projectDir = join(anvilHome, 'projects', name);
  if (!existsSync(projectDir)) {
    mkdirSync(projectDir, { recursive: true });
  }

  const factoryYamlPath = join(projectDir, 'factory.yaml');
  writeFileSync(factoryYamlPath, content, 'utf-8');
  success(`Created ${factoryYamlPath} (from template: ${templateName})`);

  console.error('');
  console.error(pc.bold('Next steps:'));
  console.error(`  1. Review: ${pc.cyan(factoryYamlPath)}`);
  console.error(`  2. Run:    ${pc.cyan(`anvil run ${name} "your feature"`)}`);
  console.error('');
}

// ── Command definition ───────────────────────────────────────────────────

export const initCommand = new Command('init')
  .description('Initialize Anvil and scaffold a project configuration')
  .option('--force', 'Overwrite existing persona prompts and configs')
  .option('--home-only', 'Only set up Anvil home directory (skip project scaffolding)')
  .option('--template <name>', 'Initialize from a template')
  .option('--list-templates', 'List available project templates')
  .action(async (opts) => {
    if (opts.listTemplates) {
      console.error('');
      console.error(pc.bold('Available Templates:'));
      for (const t of AVAILABLE_TEMPLATES) {
        console.error(`  ${pc.cyan(t)}`);
      }
      console.error('');
      console.error(`Usage: ${pc.dim('anvil init --template <name>')}`);
      console.error('');
      return;
    }

    if (opts.template) {
      await runTemplateInit(opts.template);
      return;
    }

    if (opts.homeOnly) {
      await runInit(opts.force || false);
    } else {
      await runProjectInit();
    }
  });
