/**
 * contract-test-author — render concrete test source files for a given
 * contract + scenarios, in the consumer's preferred framework.
 */

import type { Contract } from './contract-types.js';
import type { ContractTestScenario } from './contract-test-scenarios.js';

// ── Public types ────────────────────────────────────────────────────────

export type TestFramework =
  | 'vitest'
  | 'jest'
  | 'mocha'
  | 'pytest'
  | 'go-test'
  | 'junit';

export type ConsumerLanguage = 'ts' | 'js' | 'py' | 'go' | 'java';

export interface AuthoredContractTest {
  /** Repo-relative path, within the consumer repo. */
  filePath: string;
  framework: TestFramework;
  language: ConsumerLanguage;
  /** Full file contents ready to write to disk. */
  sourceCode: string;
  /** Marker line: `// anvil-contract — guards <name> endpoint <id> @ <ver>`. */
  header: string;
}

export interface AuthorInput {
  contract: Contract;
  consumerRepo: string;
  consumerLanguage: string;
  endpointId: string;
  scenarios: ContractTestScenario[];
  framework?: TestFramework;
}

// ── Entry point ─────────────────────────────────────────────────────────

export function authorContractTest(input: AuthorInput): AuthoredContractTest {
  const language = normaliseLanguage(input.consumerLanguage);
  const framework = input.framework ?? defaultFrameworkFor(language);
  const header = buildHeader(input.contract, input.endpointId, framework);
  const baseName = fileBaseName(input.contract, input.endpointId);

  switch (framework) {
    case 'vitest':
    case 'jest':
      return {
        filePath: `contract/${baseName}.contract.test.${language === 'js' ? 'js' : 'ts'}`,
        framework,
        language,
        sourceCode: renderJestLike(input, framework, header),
        header,
      };
    case 'mocha':
      return {
        filePath: `contract/${baseName}.contract.test.${language === 'js' ? 'js' : 'ts'}`,
        framework,
        language,
        sourceCode: renderMocha(input, header),
        header,
      };
    case 'pytest':
      return {
        filePath: `contract/test_${toSnake(baseName)}.py`,
        framework,
        language: 'py',
        sourceCode: renderPytest(input, header),
        header,
      };
    case 'go-test':
      return {
        filePath: `contract/${toSnake(baseName)}_contract_test.go`,
        framework,
        language: 'go',
        sourceCode: renderGoTest(input, header),
        header,
      };
    case 'junit':
      return {
        filePath: `contract/${toPascal(baseName)}ContractTest.java`,
        framework,
        language: 'java',
        sourceCode: renderJUnit(input, header),
        header,
      };
  }
}

// ── Header + defaults ───────────────────────────────────────────────────

function buildHeader(
  contract: Contract,
  endpointId: string,
  framework: TestFramework,
): string {
  const versionSuffix = contract.version ? ` @ ${contract.version}` : '';
  const body = `anvil-contract — guards ${contract.name} endpoint ${endpointId}${versionSuffix}`;
  const prefix = framework === 'pytest' ? '#' : '//';
  return `${prefix} ${body}`;
}

function defaultFrameworkFor(lang: ConsumerLanguage): TestFramework {
  switch (lang) {
    case 'ts':
    case 'js':
      return 'vitest';
    case 'py':
      return 'pytest';
    case 'go':
      return 'go-test';
    case 'java':
      return 'junit';
  }
}

function normaliseLanguage(raw: string): ConsumerLanguage {
  const lowered = raw.trim().toLowerCase();
  if (lowered === 'typescript') return 'ts';
  if (lowered === 'javascript') return 'js';
  if (lowered === 'python') return 'py';
  if (lowered === 'golang') return 'go';
  if (lowered === 'ts' || lowered === 'js' || lowered === 'py' || lowered === 'go' || lowered === 'java') {
    return lowered;
  }
  return 'ts';
}

// ── TS/JS — vitest / jest ───────────────────────────────────────────────

function renderJestLike(
  input: AuthorInput,
  framework: 'vitest' | 'jest',
  header: string,
): string {
  const importLine =
    framework === 'vitest'
      ? `import { describe, it, expect } from 'vitest';`
      : `// jest globals: describe / it / expect are in scope`;
  const blocks = input.scenarios.map((s) => renderJestIt(s)).join('\n\n');
  const suiteName = `${input.contract.name} :: ${input.endpointId}`;
  return [
    header,
    `// Generated by Anvil Contract Guard — safe to re-generate while this header is present.`,
    `// To freeze this file from re-generation, delete or alter the anvil-contract header line above.`,
    ``,
    importLine,
    ``,
    `describe(${quote(suiteName)}, () => {`,
    blocks,
    `});`,
    ``,
  ].join('\n');
}

function renderJestIt(s: ContractTestScenario): string {
  const title = quote(s.name);
  const payload = s.requestPayload !== undefined
    ? `  const requestPayload = ${toJs(s.requestPayload)};`
    : `  const requestPayload = null;`;
  const responseShape = s.expectedResponseShape !== undefined
    ? `  const expectedResponseShape = ${toJs(s.expectedResponseShape)};`
    : `  const expectedResponseShape = null;`;
  return [
    `  it(${title}, async () => {`,
    `    // ${s.description}`,
    payload,
    responseShape,
    `    // TODO(anvil): replace with a call to your client / adapter for "${s.change.path}".`,
    `    expect(requestPayload).toBeDefined();`,
    `    expect(expectedResponseShape).toBeDefined();`,
    `  });`,
  ].join('\n');
}

// ── TS/JS — mocha ───────────────────────────────────────────────────────

function renderMocha(input: AuthorInput, header: string): string {
  const blocks = input.scenarios.map((s) => renderMochaIt(s)).join('\n\n');
  const suiteName = `${input.contract.name} :: ${input.endpointId}`;
  return [
    header,
    `// Generated by Anvil Contract Guard — safe to re-generate while this header is present.`,
    ``,
    `import { strict as assert } from 'node:assert';`,
    ``,
    `describe(${quote(suiteName)}, () => {`,
    blocks,
    `});`,
    ``,
  ].join('\n');
}

function renderMochaIt(s: ContractTestScenario): string {
  const title = quote(s.name);
  const payload = s.requestPayload !== undefined
    ? `    const requestPayload = ${toJs(s.requestPayload)};`
    : `    const requestPayload = null;`;
  const responseShape = s.expectedResponseShape !== undefined
    ? `    const expectedResponseShape = ${toJs(s.expectedResponseShape)};`
    : `    const expectedResponseShape = null;`;
  return [
    `  it(${title}, async () => {`,
    `    // ${s.description}`,
    payload,
    responseShape,
    `    assert.ok(requestPayload !== undefined);`,
    `    assert.ok(expectedResponseShape !== undefined);`,
    `  });`,
  ].join('\n');
}

// ── Python — pytest ─────────────────────────────────────────────────────

function renderPytest(input: AuthorInput, header: string): string {
  const body = input.scenarios.map((s, i) => renderPytestCase(s, i)).join('\n\n');
  return [
    header,
    `# Generated by Anvil Contract Guard — safe to re-generate while this header is present.`,
    `# Contract: ${input.contract.name} endpoint ${input.endpointId}`,
    ``,
    `import pytest`,
    ``,
    body,
    ``,
  ].join('\n');
}

function renderPytestCase(s: ContractTestScenario, idx: number): string {
  const name = `test_${idx + 1}_${toSnake(s.name).slice(0, 60) || 'contract'}`;
  const payload = s.requestPayload !== undefined
    ? `    request_payload = ${toPy(s.requestPayload)}`
    : `    request_payload = None`;
  const responseShape = s.expectedResponseShape !== undefined
    ? `    expected_response_shape = ${toPy(s.expectedResponseShape)}`
    : `    expected_response_shape = None`;
  return [
    `def ${name}():`,
    `    """${s.description}"""`,
    payload,
    responseShape,
    `    # TODO(anvil): replace with a call to your client / adapter for "${s.change.path}".`,
    `    assert request_payload is not None or expected_response_shape is not None`,
  ].join('\n');
}

// ── Go — testing stdlib ─────────────────────────────────────────────────

function renderGoTest(input: AuthorInput, header: string): string {
  const body = input.scenarios.map((s, i) => renderGoCase(s, i)).join('\n\n');
  return [
    header,
    `// Generated by Anvil Contract Guard — safe to re-generate while this header is present.`,
    `// Contract: ${input.contract.name} endpoint ${input.endpointId}`,
    ``,
    `package contract`,
    ``,
    `import (`,
    `\t"testing"`,
    `)`,
    ``,
    body,
    ``,
  ].join('\n');
}

function renderGoCase(s: ContractTestScenario, idx: number): string {
  const funcName = `Test_${idx + 1}_${toPascal(s.name).slice(0, 60) || 'Contract'}`;
  const payload = s.requestPayload !== undefined
    ? `\trequestPayload := ${toGo(s.requestPayload)}`
    : `\tvar requestPayload interface{} = nil`;
  const responseShape = s.expectedResponseShape !== undefined
    ? `\texpectedResponseShape := ${toGo(s.expectedResponseShape)}`
    : `\tvar expectedResponseShape interface{} = nil`;
  return [
    `func ${funcName}(t *testing.T) {`,
    `\t// ${s.description}`,
    payload,
    responseShape,
    `\t// TODO(anvil): replace with a call to your client / adapter for "${s.change.path}".`,
    `\t_ = requestPayload`,
    `\t_ = expectedResponseShape`,
    `\tif requestPayload == nil && expectedResponseShape == nil {`,
    `\t\tt.Fatalf("contract guard: both payload and expected shape are nil")`,
    `\t}`,
    `}`,
  ].join('\n');
}

// ── Java — JUnit 5 ──────────────────────────────────────────────────────

function renderJUnit(input: AuthorInput, header: string): string {
  const className = `${toPascal(fileBaseName(input.contract, input.endpointId))}ContractTest`;
  const methods = input.scenarios.map((s, i) => renderJUnitCase(s, i)).join('\n\n');
  return [
    header,
    `// Generated by Anvil Contract Guard — safe to re-generate while this header is present.`,
    `// Contract: ${input.contract.name} endpoint ${input.endpointId}`,
    ``,
    `package contract;`,
    ``,
    `import org.junit.jupiter.api.DisplayName;`,
    `import org.junit.jupiter.api.Test;`,
    `import static org.junit.jupiter.api.Assertions.assertNotNull;`,
    ``,
    `public class ${className} {`,
    methods,
    `}`,
    ``,
  ].join('\n');
}

function renderJUnitCase(s: ContractTestScenario, idx: number): string {
  const methodName = `test_${idx + 1}_${toSnake(s.name).slice(0, 60) || 'contract'}`;
  const payloadLit = toJavaLiteral(s.requestPayload);
  const responseLit = toJavaLiteral(s.expectedResponseShape);
  return [
    `  @Test`,
    `  @DisplayName(${quote(s.name)})`,
    `  void ${methodName}() {`,
    `    // ${s.description}`,
    `    Object requestPayload = ${payloadLit};`,
    `    Object expectedResponseShape = ${responseLit};`,
    `    // TODO(anvil): replace with a call to your client / adapter for "${s.change.path}".`,
    `    assertNotNull(requestPayload != null ? requestPayload : expectedResponseShape,`,
    `      "contract guard: both payload and expected shape are null");`,
    `  }`,
  ].join('\n');
}

// ── Serializers ─────────────────────────────────────────────────────────

/** Render a JS literal from arbitrary JSON-serializable data. */
function toJs(value: unknown): string {
  return JSON.stringify(value, null, 2).replace(/\n/g, '\n    ');
}

/** Render a Python literal (dict/list/str/bool/None). */
function toPy(value: unknown): string {
  if (value === null || value === undefined) return 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return pyString(value);
  if (Array.isArray(value)) return `[${value.map((v) => toPy(v)).join(', ')}]`;
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${pyString(k)}: ${toPy(v)}`,
    );
    return `{${entries.join(', ')}}`;
  }
  return 'None';
}

/** Render a Go literal (map[string]interface{}, []interface{}, primitives). */
function toGo(value: unknown): string {
  if (value === null || value === undefined) return 'interface{}(nil)';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return goString(value);
  if (Array.isArray(value)) {
    const inner = value.map((v) => toGo(v)).join(', ');
    return `[]interface{}{${inner}}`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${goString(k)}: ${toGo(v)}`,
    );
    return `map[string]interface{}{${entries.join(', ')}}`;
  }
  return 'interface{}(nil)';
}

/** Render a Java-style literal; complex values become `new java.util.HashMap<>()`-style stubs. */
function toJavaLiteral(value: unknown): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean') return value ? 'Boolean.TRUE' : 'Boolean.FALSE';
  if (typeof value === 'number') return `Double.valueOf(${value})`;
  if (typeof value === 'string') return quote(value);
  // Arrays / objects — we just leak a sentinel; the test stub is the target.
  return `"${JSON.stringify(value).replace(/"/g, '\\"')}"`;
}

// ── Small string helpers ────────────────────────────────────────────────

function quote(s: string): string {
  return JSON.stringify(s);
}

function pyString(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function goString(s: string): string {
  return `"${s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function toSnake(s: string): string {
  return s
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function toPascal(s: string): string {
  return toSnake(s)
    .split('_')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

function fileBaseName(contract: { name: string }, endpointId: string): string {
  const raw = `${contract.name}__${endpointId}`;
  return raw.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'contract';
}
