// Build PR body with feature summary, sandbox URL, validation, cost, cross-links

export interface PrBodyContext {
  featureSummary: string;
  featureSlug: string;
  sandboxUrl?: string;
  validationSummary: string;
  cost?: { estimatedCost: number };
  crossLinks?: string[];
  runId: string;
}

/**
 * Build a comprehensive PR body including all relevant context.
 */
export function buildPrBody(context: PrBodyContext): string {
  const lines: string[] = [];

  lines.push('## Anvil PR');
  lines.push('');
  lines.push(`**Feature:** ${context.featureSlug}`);
  lines.push(`**Run ID:** ${context.runId}`);
  lines.push('');

  // Feature summary
  lines.push('### Summary');
  lines.push(context.featureSummary);
  lines.push('');

  // Sandbox
  if (context.sandboxUrl) {
    lines.push('### Sandbox Environment');
    lines.push(`[Preview Environment](${context.sandboxUrl})`);
    lines.push('');
  }

  // Validation
  lines.push('### Validation');
  lines.push(context.validationSummary);
  lines.push('');

  // Cost
  if (context.cost) {
    lines.push('### Estimated Cost');
    lines.push(`$${context.cost.estimatedCost.toFixed(2)}`);
    lines.push('');
  }

  // Cross-links
  if (context.crossLinks && context.crossLinks.length > 0) {
    lines.push('### Related PRs');
    for (const link of context.crossLinks) {
      lines.push(`- ${link}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Anvil*');

  return lines.join('\n');
}
