import { readFile, readdir, stat } from 'node:fs/promises';
import { join, basename } from 'node:path';
import YAML from 'yaml';
import type { Project } from '../project/types.js';
import { isFullstackMFE } from '../project/types.js';

export interface ClaudeMDOptions {
  project: Project;
  includedProjects?: Project[];
  globalClaudeMD?: string;
  projectDir?: string;
  projectConfigDir?: string;
}

export async function generateClaudeMD(opts: ClaudeMDOptions): Promise<string> {
  const sections: string[] = [];

  // Section 1: Header
  sections.push(`<!-- AUTO-GENERATED by Anvil — DO NOT EDIT -->
<!-- Generated: ${new Date().toISOString()} -->

# Project: ${opts.project.project}

> ${opts.project.title} — owned by ${opts.project.owner}
> Lifecycle: ${opts.project.lifecycle}${opts.project.tier ? ` | Tier: ${opts.project.tier}` : ''}
`);

  // Section 2: Global Engineering Context
  if (opts.globalClaudeMD) {
    sections.push(`## Global Engineering Context

${opts.globalClaudeMD}
`);
  }

  // Section 3: Project Architecture
  const yamlStr = YAML.stringify(opts.project, { lineWidth: 120 });
  sections.push(`## Project Architecture

\`\`\`yaml
${yamlStr.trim()}
\`\`\`
`);

  // Section 4: Included Systems
  if (opts.includedProjects && opts.includedProjects.length > 0) {
    sections.push(`## Included Systems\n`);
    for (const inc of opts.includedProjects) {
      const incYaml = YAML.stringify(inc, { lineWidth: 120 });
      sections.push(`### ${inc.project}

\`\`\`yaml
${incYaml.trim()}
\`\`\`
`);
    }
  }

  // Section 5: MFE Topology (fullstack-mfe only)
  if (isFullstackMFE(opts.project)) {
    sections.push(generateMFETopology(opts.project));
  }

  // Section 6: Active Tasks
  const activeTasksSection = await generateActiveTasksSection(opts.projectDir);
  sections.push(activeTasksSection);

  // Section 7: Cross-Project Active Tasks
  const crossTasksSection = await generateCrossSystemTasksSection(opts.projectConfigDir);
  sections.push(crossTasksSection);

  return sections.join('\n');
}

function generateMFETopology(sys: Project): string {
  const lines: string[] = ['## MFE Topology\n'];

  const containers = sys.repos.filter((r) => r.type === 'mfe-container');
  const children = sys.repos.filter((r) => r.type === 'mfe-child');
  const shared = sys.repos.filter((r) => r.type === 'mfe-shared');

  lines.push('### Container MFEs');
  for (const c of containers) {
    const port = c.frontend?.port || '?';
    lines.push(`- **${c.name}** (port: ${port})`);
    if (c.module_federation) {
      lines.push(`  - scope: \`${c.module_federation.scope}\``);
      lines.push(`  - remote_entry: \`${c.module_federation.remote_entry}\``);
    }
  }

  lines.push('\n### Child MFEs');
  for (const c of children) {
    const port = c.frontend?.port || '?';
    lines.push(`- **${c.name}** (port: ${port})`);
    if (c.module_federation) {
      lines.push(`  - scope: \`${c.module_federation.scope}\``);
      lines.push(`  - remote_entry: \`${c.module_federation.remote_entry}\``);
    }
  }

  if (shared.length > 0) {
    lines.push('\n### Shared MFE Packages');
    for (const s of shared) {
      lines.push(`- **${s.name}**`);
    }
  }

  // Routing table
  lines.push('\n### Routing Table\n');
  lines.push('| Repo | Port | Scope | Module | Remote Entry |');
  lines.push('|------|------|-------|--------|-------------|');
  for (const repo of [...containers, ...children]) {
    const port = repo.frontend?.port || '-';
    const scope = repo.module_federation?.scope || '-';
    const module_ = repo.module_federation?.module || '-';
    const remote = repo.module_federation?.remote_entry || '-';
    lines.push(`| ${repo.name} | ${port} | ${scope} | ${module_} | ${remote} |`);
  }

  lines.push('');
  return lines.join('\n');
}

async function generateActiveTasksSection(projectDir?: string): Promise<string> {
  const lines: string[] = ['## Active Tasks\n'];

  if (!projectDir) {
    lines.push('_No active tasks_\n');
    return lines.join('\n');
  }

  const tasksDir = join(projectDir, '_tasks', 'active');
  try {
    const s = await stat(tasksDir);
    if (!s.isDirectory()) {
      lines.push('_No active tasks_\n');
      return lines.join('\n');
    }

    const files = await readdir(tasksDir);
    if (files.length === 0) {
      lines.push('_No active tasks_\n');
      return lines.join('\n');
    }

    for (const file of files.sort()) {
      const content = await readFile(join(tasksDir, file), 'utf-8');
      lines.push(`### ${file}\n`);
      lines.push(content.trim());
      lines.push('');
    }
  } catch {
    lines.push('_No active tasks_\n');
  }

  return lines.join('\n');
}

async function generateCrossSystemTasksSection(projectConfigDir?: string): Promise<string> {
  const lines: string[] = ['## Cross-Project Active Tasks\n'];

  if (!projectConfigDir) {
    lines.push('_No cross-project tasks_\n');
    return lines.join('\n');
  }

  const tasksDir = join(projectConfigDir, '_tasks', 'active');
  try {
    const files = await readdir(tasksDir);
    if (files.length === 0) {
      lines.push('_No cross-project tasks_\n');
      return lines.join('\n');
    }

    for (const file of files.sort()) {
      lines.push(`- ${basename(file)}`);
    }
    lines.push('');
  } catch {
    lines.push('_No cross-project tasks_\n');
  }

  return lines.join('\n');
}
