import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export interface PRInfo {
  repoName: string;
  url: string;
  number: number;
}

type ExecCommand = (cmd: string, args: string[]) => Promise<{ stdout: string; stderr: string }>;

const defaultExecCommand: ExecCommand = async (cmd, args) => {
  const { stdout, stderr } = await execFileAsync(cmd, args, {
    maxBuffer: 10 * 1024 * 1024,
    timeout: 2 * 60_000,
  });
  return { stdout, stderr };
};

function buildPRBody(
  validationSummary: string,
  sandboxUrl?: string,
  cost?: { estimatedCost: number },
): string {
  const lines: string[] = [
    '## Anvil PR',
    '',
    '### Validation Summary',
    validationSummary,
    '',
  ];

  if (sandboxUrl) {
    lines.push('### Sandbox');
    lines.push(`[Preview Environment](${sandboxUrl})`);
    lines.push('');
  }

  if (cost) {
    lines.push('### Cost');
    lines.push(`Estimated cost: $${cost.estimatedCost.toFixed(2)}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Anvil*');

  return lines.join('\n');
}

/**
 * Creates pull requests using `gh pr create` for each repo.
 */
export async function createPullRequests(
  runId: string,
  featureSlug: string,
  repoPaths: Record<string, string>,
  branchName: string,
  validationSummary: string,
  sandboxUrl?: string,
  cost?: { estimatedCost: number },
  execCommand: ExecCommand = defaultExecCommand,
  labels?: string[],
): Promise<PRInfo[]> {
  const prInfos: PRInfo[] = [];
  const body = buildPRBody(validationSummary, sandboxUrl, cost);
  const title = `[FF] ${featureSlug}`;

  for (const [repoName, repoPath] of Object.entries(repoPaths)) {
    try {
      const args = [
        'pr',
        'create',
        '--title',
        title,
        '--body',
        body,
        '--head',
        branchName,
        '--repo',
        repoName,
      ];
      if (labels && labels.length > 0) {
        for (const label of labels) {
          args.push('--label', label);
        }
      }
      const { stdout } = await execCommand('gh', args);

      // Parse PR URL and number from gh output
      const urlMatch = stdout.match(/https:\/\/github\.com\/[^\s]+\/pull\/(\d+)/);
      const url = urlMatch ? urlMatch[0] : stdout.trim();
      const number = urlMatch ? parseInt(urlMatch[1], 10) : 0;

      prInfos.push({ repoName, url, number });
    } catch (error) {
      // If PR creation fails, still continue with other repos
      prInfos.push({
        repoName,
        url: '',
        number: 0,
      });
    }
  }

  return prInfos;
}
